-- Routine app: tables, row-level security and the CSV-replace function.
-- Supabase dashboard -> SQL Editor -> paste this whole file -> Run. Safe to re-run.

-- ---------- tables ----------

-- One row per completed session (append-only). The id is generated by the app,
-- so retrying a push can never create a duplicate.
create table if not exists public.sessions (
  id          uuid primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  date        date not null,
  routine     text not null,              -- 'A', 'B' or 'D' (daily only)
  version     int,                        -- CSV version at the time
  exercises   jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now()
);
create index if not exists sessions_user_date_idx on public.sessions (user_id, date);

-- The current exercise list (what you last imported from CSV).
create table if not exists public.exercises (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  position     int  not null,             -- keeps CSV order
  exercise     text not null,
  routine      text not null,             -- 'A', 'B' or 'daily'
  details      text not null default '',
  version      int,
  csv_hash     text,
  imported_at  timestamptz not null default now()
);
create index if not exists exercises_user_pos_idx on public.exercises (user_id, position);

-- Remove any exact duplicates created before uniqueness was enforced, keeping
-- one deterministic row for each user's exercise/routine/details combination.
delete from public.exercises older
using public.exercises newer
where older.user_id = newer.user_id
  and older.exercise = newer.exercise
  and older.routine = newer.routine
  and older.details = newer.details
  and older.id > newer.id;

create unique index if not exists exercises_user_content_unique_idx
  on public.exercises (user_id, exercise, routine, details);

-- ---------- row-level security: you only ever see and change your own rows ----------

alter table public.sessions  enable row level security;
alter table public.exercises enable row level security;

drop policy if exists "own sessions" on public.sessions;
create policy "own sessions" on public.sessions
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "own exercises" on public.exercises;
create policy "own exercises" on public.exercises
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- Explicit grants (harmless if already present; needed if the project doesn't auto-expose new tables).
grant select, insert, update, delete on public.sessions  to authenticated;
grant select, insert, update, delete on public.exercises to authenticated;

-- ---------- replace the whole exercise list in one transaction ----------
-- A failed import can't leave you with an empty list. Runs as the caller, so RLS applies.

create or replace function public.replace_exercises(
  p_rows        jsonb,
  p_imported_at timestamptz,
  p_version     int,
  p_hash        text
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  delete from public.exercises where user_id = auth.uid();

  insert into public.exercises (position, exercise, routine, details, version, csv_hash, imported_at)
  select (t.ord - 1)::int,
         t.r ->> 'exercise',
         t.r ->> 'routine',
         coalesce(t.r ->> 'details', ''),
         p_version,
         p_hash,
         p_imported_at
  from jsonb_array_elements(p_rows) with ordinality as t(r, ord);
end;
$$;

revoke execute on function public.replace_exercises(jsonb, timestamptz, int, text) from public, anon;
grant  execute on function public.replace_exercises(jsonb, timestamptz, int, text) to authenticated;
